version: '3.3'
services:
    # MySQL
    mysql_db:
        image: mysql:latest
        volumes:
            - "./dckr_database/mysql/database_prod.sql:/docker-entrypoint-initdb.d/0_init.sql"
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        container_name: mysql_db
        networks:
            - mediscreen-network

    # MongoDB
    mongo_db:
        image: mongo:latest
        hostname: mongo_db
        volumes:
            - ./dckr_database/mongodb/mongod.conf:/etc/mongod.conf
            - ./dckr_database/mongodb/data/db/:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        container_name: mongo_db
        command: ["-f", "/etc/mongod.conf"]
        networks:
            - mediscreen-network

    # MongoDB - Data
    mongo_db_data:
        image: mongo:latest
        container_name: mongo_db_data
        volumes:
            - ./dckr_database/mongodb/init/:/src/data/
        command: ./src/data/import.sh 
        depends_on:
            - mongo_db
        networks:
            - mediscreen-network    

    # ems-eureka
    ems-eureka:
        build: ./edge-microservices/ems-eureka/
        restart: always
        ports:
            - "9001:9001"
        container_name: ems-eureka
        networks:
            - mediscreen-network

    # ems-zuul
    ems-zuul:
        build: ./edge-microservices/ems-zuul/
        restart: always
        ports:
            - "9002:9002"
        container_name: ems-zuul
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - ems-eureka
        networks:
            - mediscreen-network
    
    # ems-admin
    ems-admin:
        build: ./edge-microservices/ems-admin/
        restart: always
        ports:
            - "9003:9003"
        container_name: ems-admin
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - ems-eureka
        networks:
            - mediscreen-network

    # ms-authentication
    ms-authentication:
        build: ./ms-authentication/
        restart: always
        ports:
            - "8083:8083"
        container_name: ms-authentication
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - ems-eureka
        networks:
            - mediscreen-network

    # ms-patientadmin
    ms-patientadmin:
        build: ./ms-patientAdmin/
        restart: always
        ports:
            - "8081:8081"
        container_name: ms-patientadmin
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
            - mediscreen-ms-patient-admin-db.host=mysql_db
        depends_on:
            - ems-eureka
            - mysql_db
        networks:
            - mediscreen-network

    # ms-medicalrecord
    ms-medicalrecord:
        build: ./ms-medicalrecord/
        restart: always
        ports:
            - "8082:8082"
        container_name: ms-medicalrecord
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
            - mediscreen-ms-medical-record-db.host=mongo_db
        depends_on:
            - ems-eureka
            - mongo_db
        networks:
            - mediscreen-network

    # ms-medicalreport
    ms-medicalreport:
        build: ./ms-medicalreport/
        restart: always
        ports:
            - "8084:8084"
        container_name: ms-medicalreport
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - ems-eureka
        networks:
            - mediscreen-network

    # ms-clientui
    ms-clientui:
        build: ./ms-clientui/
        restart: always
        ports:
            - "8888:8888"
        container_name: ms-clientui
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - ems-eureka
        networks:
            - mediscreen-network
networks:
    mediscreen-network:
        driver: bridge