version: '3.3'
services:
    mysql_db:
        image: mysql:latest
        volumes:
            - "./mediscreen-patient/src/main/resources/static/database/patient_data.sql:/docker-entrypoint-initdb.d/0_init.sql"
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        container_name: mysql_db
        networks:
            - mediscreen-network

    #eureka
    eureka-server:
        build: ./edge-microservices/eureka-server/
        restart: always
        ports: 
            - "9001:9001"
        container_name: eureka-server
        networks:
            - mediscreen-network

    # zuul
    zuul-server:
        build: ./edge-microservices/zuul-server/
        restart: always
        ports: 
            - "9002:9002"
        container_name: ems-zuul
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - eureka-server
        networks:
            - mediscreen-network
    
    #ems-admin
    admin-service:
        build: ./edge-microservices/admin-service/
        restart: always
        ports: 
            - "9004:9004"
        container_name: ems-admin
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - eureka-server
        networks:
            - mediscreen-network

    #authentication
    mediscreen-authentication:
        build: ./mediscreen-authentication/
        restart: always
        ports: 
            - "8081:8081"
        container_name: ms-authentication
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - eureka-server
        networks:
            - mediscreen-network

    #patient 
    mediscreen-patient:
        build: ./mediscreen-patient/
        restart: always
        ports: 
            - "8082:8082"
        container_name: ms-patient
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
            - mediscreen-mediscreen-patient-db.host=mysql_db
        depends_on:
            - eureka-server
            - mysql_db
        networks:
            - mediscreen-network

  #clientui
    mediscreen-clientui:
        build: ./ms-clientui/
        restart: always
        ports:
            - "8888:8888"
        container_name: ms-clientui
        environment:
            - eureka.client.serviceUrl.defaultZone=http://ems-eureka:9001/eureka/
        depends_on:
            - eureka-server
        networks:
            - mediscreen-network
networks:
    mediscreen-network:
        driver: bridge